### ISSUE TITLE
local file not merging.

### ISSUE THREAD

**Issue by mona-a** [mona-a/RepLikeGirl#1]
@DeAngelisA 
seems I got this wrong, can you help please? I just forked my file to Unilu so you can access too.

I've been working locally, at some point I installed GitHub desktop which was probably a bad idea cause now I have the old version of my .Rmd in my master,  the new and corrected version is local and I cannot push it. Now I only need to put the correct file into master (Source/Repl_ResearchLikeGirl.Rmd):

1: I checked status and deleted all wrong files (starting with 1 and 2) to have a tidy structure
----
(base) Foggs-MacBook-Pro:RepLikeGirl msfogg$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 3 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
	new file:   1 originalData/Readme.md
	new file:   1 originalData/Replication Data for: You Research Like a Girl: Gendered Research Agendas and Their Implications - PS: Political Science & Politics.pdf
	new file:   1 originalData/dissertation-data-clean.csv
	new file:   1 originalData/output-for-figure.csv
	new file:   1 originalData/plot-file.R
	new file:   1 originalData/you_research_like_a_girl_gendered_research_agendas_and_their_implications.pdf
	new file:   1 originalData/yrlag-clean.R
	new file:   2 STM documentation/stm copy.pdf
	new file:   2 STM documentation/stm pitch.pdf
	new file:   2 STM documentation/stmVignette.pdf

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both added:      Source/Repl_ResearchLikeGirl.Rmd

----

2. tried to add my file:

error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.
(base) Foggs-MacBook-Pro:RepLikeGirl msfogg$ git add source/Repl_ResearchLikeGirl.Rmd
(base) Foggs-MacBook-Pro:RepLikeGirl msfogg$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 3 and 11 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean
---

But is still the wrong file on Github.

**Comment by mona-a** [comment]
gave in to fate and
git reset --hard origin/master

saved my file elsewhere, replacing now

**Comment by DeAngelisA** [comment]
Try `git pull --rebase`.
Otherwise, you may do `git reset --hard origin/master` **but** this would loose all changes not pushed to `origin/master`. I am sending an email.

**Comment by mona-a** [comment]
Thanks … was trying to avoid this but did it and worked kinda.

On 25 May 2020, at 16:51, Andrea De Angelis <notifications@github.com<mailto:notifications@github.com>> wrote:



Try git rebase origin/master.
Otherwise, you may do git reset --hard origin/master but this would loose all changes not pushed to origin/master. I am sending an email.
